# Network & General
tcp-keepalive 300
timeout 0
loglevel notice

# Memory Management
maxmemory 256mb
maxmemory-policy allkeys-lru

# Persistence (Append Only File)
appendonly yes
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# Snapshotting (RDB)
save 900 1
save 300 10
save 60 10000
dbfilename dump.rdb
dir /data
